theme: jekyll-theme-chirpy
lang: zh-CN
timezone: Asia/Shanghai
title: gaoshouq
tagline: 个人技术博客
description: >-
  分享技术笔记与生活感悟
url: "https://xvexige.github.io"
github:
  username: xvexige
social:
  name: gaoshouq
  email: 2241123028@qq.com
  links:
    - https://github.com/xvexige
theme_mode: dark
avatar: "https://www.bing.com/images/search?view=detailV2&ccid=o9aMZte0&id=AFAA897B4DCA8B0C7E140B137D1B67905D0E19AD&thid=OIP.o9aMZte0s3RpLbGxaI7W4wHaQC&mediaurl=https%3a%2f%2fc-ssl.dtstatic.com%2fuploads%2fblog%2f202209%2f09%2f20220909205019_93c08.thumb.1000_0.jpeg&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.a3d68c66d7b4b374692db1b1688ed6e3%3frik%3drRkOXZBnG30TCw%26pid%3dImgRaw%26r%3d0&exph=2165&expw=1000&q=%e6%b5%b7%e8%b4%bc%e7%8e%8b%e5%9b%be%e7%89%87&FORM=IRPRST&ck=083F4FA600437D30117B07BDBC960E7A&selectedIndex=120&itb=0"
toc: true
pwa:
  enabled: true
paginate: 10
baseurl: ""
kramdown:
  syntax_highlighter: rouge
collections:
  tabs:
    output: true
    sort_by: order
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
sass:
  style: compressed
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - "package*.json"
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
