theme: jekyll-theme-chirpy
lang: zh-CN
timezone: Asia/Shanghai
title: gaoshouq
tagline: 个人技术博客
description: >-
  分享技术笔记与生活感悟
url: "https://xvexige.github.io"
github:
  username: xvexige
social:
  name: gaoshouq
  email: 2241123028@qq.com
  links:
    - https://github.com/xvexige
theme_mode: dark
avatar: ""
toc: true
pwa:
  enabled: true
paginate: 10
baseurl: ""
kramdown:
  syntax_highlighter: rouge
collections:
  tabs:
    output: true
    sort_by: order
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
sass:
  style: compressed
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - "package*.json"
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
